version: 2
updates:
# Fetch and update latest `npm` packages
- package-ecosystem: npm
  directory: '/'
  schedule:
    interval: weekly
    time: '03:00'
    timezone: "America/Los_Angeles"
  open-pull-requests-limit: 10
  reviewers:
    - gwelican
  assignees:
    - gwelican
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
# Fetch and update latest `github-actions` pkgs
- package-ecosystem: github-actions
  directory: '/'
  schedule:
    interval: daily
    time: '03:00'
    timezone: "America/Los_Angeles"
  open-pull-requests-limit: 10
  reviewers:
    - gwelican
  assignees:
    - gwelican
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
